# Generated by Django 5.1.5 on 2025-02-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.IntegerField()),
                ('line_numb', models.IntegerField()),
                ('operator_id', models.IntegerField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('login_time', models.TimeField()),
                ('mode', models.IntegerField()),
                ('stitch_count', models.IntegerField()),
                ('needle_runtime', models.FloatField()),
                ('needle_stoptime', models.FloatField()),
                ('tx_logid', models.IntegerField()),
                ('str_logid', models.IntegerField()),
                ('device_id', models.IntegerField()),
                ('reserve', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.IntegerField(unique=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
