# Generated by Django 5.1.5 on 2025-02-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='machinelog',
            unique_together={('machine_id', 'operator_id', 'start_time', 'end_time')},
        ),
    ]
