# Generated by Django 5.1.6 on 2025-02-25 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_rename_date_machinelog_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='machinelog',
            unique_together={('MACHINE_ID', 'OPERATOR_ID', 'DATE', 'START_TIME', 'END_TIME')},
        ),
    ]
