# Generated by Django 5.1.6 on 2025-03-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_alter_machinelog_operator_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='machinelog',
            unique_together=set(),
        ),
    ]
