# Generated by Django 5.1.6 on 2025-03-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_alter_machinelog_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinelog',
            name='OPERATOR_ID',
            field=models.BigIntegerField(),
        ),
    ]
