# Generated by Django 5.1.6 on 2025-03-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_alter_machinelog_operator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinelog',
            name='OPERATOR_ID',
            field=models.CharField(max_length=30),
        ),
    ]
