# Generated by Django 5.0.4 on 2025-05-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinelog',
            name='DATE',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='MODE',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='machinelog',
            index=models.Index(fields=['DATE'], name='logs_machin_DATE_2807c4_idx'),
        ),
        migrations.AddIndex(
            model_name='machinelog',
            index=models.Index(fields=['created_at'], name='logs_machin_created_496429_idx'),
        ),
        migrations.AddIndex(
            model_name='machinelog',
            index=models.Index(fields=['MODE'], name='logs_machin_MODE_b3338b_idx'),
        ),
    ]
