# Generated by Django 5.0.4 on 2025-05-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0012_adminuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMachineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MACHINE_ID', models.IntegerField()),
                ('LINE_NUMB', models.IntegerField()),
                ('OPERATOR_ID', models.CharField(max_length=30)),
                ('DATE', models.DateField(db_index=True)),
                ('START_TIME', models.TimeField()),
                ('END_TIME', models.TimeField()),
                ('MODE', models.IntegerField(db_index=True)),
                ('STITCH_COUNT', models.IntegerField()),
                ('NEEDLE_RUNTIME', models.FloatField()),
                ('NEEDLE_STOPTIME', models.FloatField()),
                ('Tx_LOGID', models.IntegerField()),
                ('Str_LOGID', models.IntegerField()),
                ('DEVICE_ID', models.IntegerField()),
                ('RESERVE', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['DATE'], name='logs_userma_DATE_2bd071_idx'), models.Index(fields=['created_at'], name='logs_userma_created_097f96_idx'), models.Index(fields=['MODE'], name='logs_userma_MODE_c76330_idx')],
            },
        ),
    ]
