# Generated by Django 5.0.4 on 2025-05-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0013_usermachinelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorAFL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_card_no', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
