# Generated by Django 5.0.4 on 2025-05-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0014_operatorafl'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorafl',
            name='operatorAFL_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
