# Generated by Django 5.0.4 on 2025-05-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0015_operatorafl_operatorafl_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='duplicatelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the duplicate was logged'),
        ),
        migrations.AlterField(
            model_name='duplicatelog',
            name='payload',
            field=models.JSONField(help_text='JSON data of the duplicate submission'),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='DATE',
            field=models.DateField(db_index=True, help_text='Date when the operation was performed'),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='DEVICE_ID',
            field=models.IntegerField(help_text='Unique identifier for the device component'),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='END_TIME',
            field=models.TimeField(help_text='Time when operation ended'),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='LINE_NUMB',
            field=models.IntegerField(help_text='Production line number where the machine is located'),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='MACHINE_ID',
            field=models.IntegerField(help_text='Unique identifier for the machine'),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='MODE',
            field=models.IntegerField(db_index=True, help_text='Operational mode of the machine'),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='NEEDLE_RUNTIME',
            field=models.FloatField(help_text='Duration (in seconds) the needle was operational'),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='NEEDLE_STOPTIME',
            field=models.FloatField(help_text='Duration (in seconds) the needle was stopped'),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='OPERATOR_ID',
            field=models.CharField(help_text='Identifier for the operator using the machine', max_length=30),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='RESERVE',
            field=models.TextField(blank=True, help_text='Additional information or notes (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='START_TIME',
            field=models.TimeField(help_text='Time when operation started'),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='STITCH_COUNT',
            field=models.IntegerField(help_text='Number of stitches performed during operation'),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='Str_LOGID',
            field=models.IntegerField(help_text='Storage log identifier'),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='Tx_LOGID',
            field=models.IntegerField(help_text='Transaction log identifier'),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='modemessage',
            name='message',
            field=models.TextField(help_text='Description or message associated with this mode'),
        ),
        migrations.AlterField(
            model_name='modemessage',
            name='mode',
            field=models.IntegerField(help_text='Unique mode identifier number', unique=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='operator_name',
            field=models.CharField(help_text='Full name of the operator', max_length=50),
        ),
        migrations.AlterField(
            model_name='operator',
            name='remarks',
            field=models.CharField(blank=True, help_text='Additional notes about the operator', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='rfid_card_no',
            field=models.CharField(help_text='Unique RFID card number assigned to the operator', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='operatorafl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the operator account was created'),
        ),
        migrations.AlterField(
            model_name='operatorafl',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the operator account is currently active'),
        ),
        migrations.AlterField(
            model_name='operatorafl',
            name='operatorAFL_name',
            field=models.CharField(default='', help_text='Full name of the AFL operator', max_length=50),
        ),
        migrations.AlterField(
            model_name='operatorafl',
            name='rfid_card_no',
            field=models.CharField(help_text='Unique RFID card number assigned to the AFL operator', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='DATE',
            field=models.DateField(db_index=True, help_text='Date when the operation was performed'),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='DEVICE_ID',
            field=models.IntegerField(help_text='Unique identifier for the device component'),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='END_TIME',
            field=models.TimeField(help_text='Time when operation ended'),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='LINE_NUMB',
            field=models.IntegerField(help_text='Production line number where the machine is located'),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='MACHINE_ID',
            field=models.IntegerField(help_text='Unique identifier for the machine'),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='MODE',
            field=models.IntegerField(db_index=True, help_text='Operational mode of the machine'),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='NEEDLE_RUNTIME',
            field=models.FloatField(help_text='Duration (in seconds) the needle was operational'),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='NEEDLE_STOPTIME',
            field=models.FloatField(help_text='Duration (in seconds) the needle was stopped'),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='OPERATOR_ID',
            field=models.CharField(help_text='Identifier for the operator using the machine', max_length=30),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='RESERVE',
            field=models.TextField(blank=True, help_text='Additional information or notes (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='START_TIME',
            field=models.TimeField(help_text='Time when operation started'),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='STITCH_COUNT',
            field=models.IntegerField(help_text='Number of stitches performed during operation'),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='Str_LOGID',
            field=models.IntegerField(help_text='Storage log identifier'),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='Tx_LOGID',
            field=models.IntegerField(help_text='Transaction log identifier'),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created'),
        ),
    ]
