# Generated by Django 5.0.4 on 2025-05-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0016_delete_adminuser_delete_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='duplicatelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='duplicatelog',
            name='payload',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='DATE',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='DEVICE_ID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='END_TIME',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='LINE_NUMB',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='MACHINE_ID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='MODE',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='NEEDLE_RUNTIME',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='NEEDLE_STOPTIME',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='OPERATOR_ID',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='RESERVE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='START_TIME',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='STITCH_COUNT',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='Str_LOGID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='Tx_LOGID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='machinelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='modemessage',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='modemessage',
            name='mode',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='operator_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='operator',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='rfid_card_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='operatorafl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='operatorafl',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='operatorafl',
            name='operatorAFL_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='operatorafl',
            name='rfid_card_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='DATE',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='DEVICE_ID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='END_TIME',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='LINE_NUMB',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='MACHINE_ID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='MODE',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='NEEDLE_RUNTIME',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='NEEDLE_STOPTIME',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='OPERATOR_ID',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='RESERVE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='START_TIME',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='STITCH_COUNT',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='Str_LOGID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='Tx_LOGID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usermachinelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
